matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - "node_modules"
      jobs:
        include:
          - stage: Installing dependencies...
            script: yarn install
          - stage: Unit Tests
            script: yarn test
          # - stage: Produce Coverage
          #   script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - os: linux
      language: python
      python:
        - "2.7"
      install:
        - pip install -r requirements.txt
        - pip install .
      jobs:
        include:
          - stage: Installing dependencies...
            script:
              - pip install awscli
              - pip install aws-sam-cli
          - stage: SAM Validate
            script: sam validate
          - stage: Deploy to aws
            if: branch = master
            env:
              - ENV=dev DEPLOY_BUCKET=fp95-code-deploy    
            script: bash scripts/deploy.sh     

