matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - "node_modules"
      jobs:
        include:
          - stage: Installing dependencies...
            script: yarn install
          - stage: Unit Tests
            script: yarn test
          # - stage: Produce Coverage
          #   script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - language: python
      python:
        - "2.7"
      branches:
        only:
          - master
      before_install:
        - cd scripts
      install:
        - pip install awscli
        - pip install aws-sam-cli
      script:
        - sam validate
      deploy:
        provider: script
        script: deploy.sh
        on:
          branch: master
        env:
          - ENV=dev DEPLOY_BUCKET=fp95-code-deploy          

