language: node_js
node_js:
  - "stable"

cache:
directories:
  - node_modules

before_install:
  - npm install
  - npm run test
install:
  - npm run build



# deploy:
#   provider: script
#   script: bash scripts/deploy.sh
#   on:
#     branch: master
#   env:
#     - ENV=dev DEPLOY_BUCKET=fp95-code-deploy

# language: node_js
# os: linux
# node_js:
#   - "stable"
# cache:
#   directories:
#     - "node_modules"
# jobs:
#   include:
#     - stage: Installing CLIs...
#       script:
#         - yes '' | sudo -H add-apt-repository ppa:deadsnakes/ppa
#         - sudo -H apt update
#         - sudo -H apt install python3.6
#         - python -V
#         - sudo -H apt install python3-pip python3-setuptools python3-wheel
#         - sudo -H pip3 install --upgrade pip
#         - sudo -H pip3 install awscli
#         - aws --version
#         - sudo -H pip3 install aws-sam-cli
#         - sam --version
#     - stage: Validating template...
#       script: sam validate --template scripts/template.yaml
#     - stage: Installing dependencies...
#       script: yarn install
#     - stage: Unit Tests
#       script: yarn run test
#     - stage: Produce Coverage
#       script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
# deploy:
#   provider: script
#   script: bash scripts/deploy.sh
#   on:
#     branch: master
#   env:
#     - ENV=dev DEPLOY_BUCKET=fp95-code-deploy

# matrix:
#   include:
#     - language: node_js
#       node_js:
#         - "stable"
#       cache:
#         directories:
#           - "node_modules"
#       jobs:
#         include:
#           - stage: Installing dependencies...
#             script: yarn install
#           - stage: Unit Tests
#             script: yarn test
#           # - stage: Produce Coverage
#           #   script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
#     - language: python
#       python:
#         - "3.6"
#       branches:
#         only:
#           - master
#       install:
#         - pip3 install awscli
#         - pip3 install aws-sam-cli

#         # JavaScript requirements
#         - sudo add-apt-repository -y ppa:chris-lea/node.js
#         - sudo apt-get -y update
#         - sudo apt-get -y install nodejs
#         - sudo npm install -g npx
#       script:
#         - sam validate --template scripts/template.yaml
#       before_deploy:
#         on:
#           branch: master
#         script:
#           - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
#           - command -v nvm
#       deploy:
#         provider: script
#         script: bash scripts/deploy.sh
#         on:
#           branch: master
#         env:
#           - ENV=dev DEPLOY_BUCKET=fp95-code-deploy