AWSTemplateFormatVersion: "2010-09-09"
Description: Frontend Assessment

Parameters:
  Environment:
    Type: String
  Project:
    Type: String
  DeployBucket:
    Type: String
  DomainBucket:
    Type: String
  LogBucket:
    Type: String
  LogsUserArn:
    Type: String

Resources:
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt MyStaticSiteBucket.DomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: 'true'
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: 'false'
          Bucket: !GetAtt MyLogBucket.DomainName
          Prefix: !Ref Environment
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
    DependsOn:
      - MyStaticSiteBucket
      - MyLogBucket
  MyStaticSiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref DomainBucket
      WebsiteConfiguration:
        IndexDocument: index.html
  MyLogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref LogBucket
    DependsOn:
      - MyStaticSiteBucket
  MyStaticSiteBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyStaticSiteBucket
      PolicyDocument:
        Statement:
          - Sid: ReadAccess
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub 'arn:aws:s3:::${DomainBucket}/*'
            Principal: "*"
          - Sid: ListWriteDeleteAccess
            Action:
              - "s3:ListBucket"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Effect: "Allow"
            Resource:
              - !Sub 'arn:aws:s3:::${DomainBucket}/*'
              - !Sub 'arn:aws:s3:::${DomainBucket}'
            Principal:
                AWS: !Ref LogsUserArn
  MyLogBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyLogBucket
      PolicyDocument:
        Statement:
          - Sid: ListReadWriteDeleteAccess
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Effect: "Allow"
            Resource:
              - !Sub 'arn:aws:s3:::${LogBucket}/*'
              - !Sub 'arn:aws:s3:::${LogBucket}'
            Principal:
                AWS: !Ref LogsUserArn

Outputs:
  CloudFrontDistributionOutput:
    Description: CloudFront Distribution
    Value: !Ref myDistribution
    Export:
      Name: !Join ["-", [!Ref Environment, "PortalDistribution", !Ref Project]]